<?xml version="1.0" encoding="utf-8"?><Database Name="JKDec20" Class="EmployeeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\MsSqlLocalDb;Initial Catalog=JKDec20;Integrated Security=True;Pooling=False" SettingsObjectName="WpfApp1.Properties.Settings" SettingsPropertyName="JKDec20ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="EmpNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EmpName" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Basic" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="DeptNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Department_Employee" Member="Department" ThisKey="DeptNo" OtherKey="DeptNo" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DeptNo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeptName" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="Department_Employee" Member="Employees" ThisKey="DeptNo" OtherKey="DeptNo" Type="Employee" />
    </Type>
  </Table>
</Database>